### ISSUE TITLE
Can we update the requirements at min_requirements.constraints?

### ISSUE THREAD

**Issue by 5thsymphony** [tophat/ormar-postgres-extensions#12]
### What is your question?

The requirements here are out of date: https://github.com/tophat/ormar-postgres-extensions/blob/main/min_requirements.constraints

Can they be updated and a new release rolled when you get a moment please. Currently these cause poetry to pull in older versions when you install this extension.

**Comment by etimberg** [comment]
Will the update from #9 fix the constraint file for you?

**Comment by 5thsymphony** [comment]
Yes please, I'm not sure those are the latest available versions however.

I have also added support for JSON fields on my temporary fork, I'll clean up and get a pull request in.

Not sure if it is out of scope but I also added support for the ormar-postgres-ext field JSONB.

Thanks for your time.

**Comment by etimberg** [comment]
I released #9 in v2.1.0 so this should be good to go
