### ISSUE TITLE
Import Issue

### ISSUE THREAD

**Issue by notnil** [tophat/ormar-postgres-extensions#19]
### What is your question?

```
from sqlalchemy.dialects.postgres import array
```

How do I actually install this?

**Comment by etimberg** [comment]
@notnil it should already be installed since `ormar` itself needs it. If not, you can do `pip install sqlalchemy`

**Comment by notnil** [comment]
```
from sqlalchemy.dialects.postgresql import array
```

This fixed it ^

**Comment by etimberg** [comment]
Oh I see 🤦‍♂️. I made a typo in the docs. Will fix that
