### ISSUE TITLE
Consider supporting Pydantic 2.0? 

### ISSUE THREAD

**Issue by ker-zhao** [tophat/ormar-postgres-extensions#32]
### Is your feature request related to a problem? Please describe.

Hi, there. I'm using this extension, thanks a lot. 
The package is not compatible with Pydantic 2.0 when I try to update pydantic to 2.0 with Poetry.
Would you consider supporting Pydantic 2.0?

**Comment by etimberg** [comment]
@ker-zhao thanks for filing this. Unfortunately I'm no longer at Top Hat so I don't know how this package is being used internally. That being said, I can take a look at updating this to pydantic 2.0 but it might take a few weeks as I'm moving soon and don't have a ton of free time

**Comment by noahnu** [comment]
@etimberg I'll follow up internally as well

**Comment by noahnu** [comment]
Update on my end: we use this project with fastapi and since pydantic 2 support in fastapi is still experimental, we will not be picking this up just yet. That being said, if you're interested in opening a pull request, contributions are welcome.
